ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_MEME_KEY FOREIGN KEY (MEME_KEY) REFERENCES GOLD.DIM_MEMBER (MEME_KEY);
ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_PLPL_KEY FOREIGN KEY (PLPL_KEY) REFERENCES GOLD.DIM_PLAN (PLPL_KEY);
ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_GRGR_KEY FOREIGN KEY (GRGR_KEY) REFERENCES GOLD.DIM_GROUP (GRGR_KEY);
ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_COVERAGE_START_DATE_KEY FOREIGN KEY (COVERAGE_START_DATE_KEY) REFERENCES GOLD.DIM_DATE (DATE_KEY);
ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_COVERAGE_END_DATE_KEY FOREIGN KEY (COVERAGE_END_DATE_KEY) REFERENCES GOLD.DIM_DATE (DATE_KEY);
ALTER TABLE GOLD.FACT_ENROLLMENT ADD CONSTRAINT FK_FACT_ENROLLMENT_TXN_SRC_KEY FOREIGN KEY (TXN_SRC_KEY) REFERENCES GOLD.DIM_TRANSACTION_SOURCE (TXN_SRC_KEY);
