CREATE TABLE IF NOT EXISTS GOLD.DIM_DATE (
  DATE_KEY INT PRIMARY KEY NOT NULL,
  FULL_DATE DATE NOT NULL,
  YEAR_NUMBER INT NOT NULL,
  QUARTER_NUMBER INT NOT NULL,
  MONTH_NUMBER INT NOT NULL,
  DAY_NUMBER INT NOT NULL,
  DAY_OF_WEEK_NAME STRING NOT NULL
)
USING DELTA
COMMENT 'Gold date dimension. DATE_KEY uses YYYYMMDD format (e.g., 20260827 = 27-Aug-2026).';
