DROP TABLE IF EXISTS GOLD.FACT_ENROLLMENT;
DROP TABLE IF EXISTS GOLD.DIM_TRANSACTION_SOURCE;
DROP TABLE IF EXISTS GOLD.DIM_DATE;
DROP TABLE IF EXISTS GOLD.DIM_PLAN;
DROP TABLE IF EXISTS GOLD.DIM_GROUP;
DROP TABLE IF EXISTS GOLD.DIM_MEMBER;

DROP TABLE IF EXISTS SILVER.REJECT;
DROP TABLE IF EXISTS SILVER.TRANSACTION;
DROP TABLE IF EXISTS SILVER.ADDRESS;
DROP TABLE IF EXISTS SILVER.ENROLLMENT;
DROP TABLE IF EXISTS SILVER.PLAN;
DROP TABLE IF EXISTS SILVER.GROUP;
DROP TABLE IF EXISTS SILVER.SUBSCRIBER;
DROP TABLE IF EXISTS SILVER.MEMBER;

DROP TABLE IF EXISTS BRONZE.IMM_INGESTION_AUDIT;
DROP TABLE IF EXISTS BRONZE.IMM_834_SEGMENT;
DROP TABLE IF EXISTS BRONZE.IMM_834_TRANSACTION;
DROP TABLE IF EXISTS BRONZE.IMM_834_RAW;

DROP SCHEMA IF EXISTS GOLD CASCADE;
DROP SCHEMA IF EXISTS SILVER CASCADE;
DROP SCHEMA IF EXISTS BRONZE CASCADE;
