-- INDEXES --------------------------------------------------------------------

DROP INDEX IF EXISTS IX_CORE_GRGR_GROUP_ST_CD;
CREATE INDEX IX_CORE_GRGR_GROUP_ST_CD ON CORE.CORE_GRGR_GROUP (ST_CD);

DROP INDEX IF EXISTS IX_CORE_PLPL_PLAN_LOB_CD;
CREATE INDEX IX_CORE_PLPL_PLAN_LOB_CD ON CORE.CORE_PLPL_PLAN (LOB_CD);
DROP INDEX IF EXISTS IX_CORE_PLPL_PLAN_EFF_DT;
CREATE INDEX IX_CORE_PLPL_PLAN_EFF_DT ON CORE.CORE_PLPL_PLAN (EFF_DT);

DROP INDEX IF EXISTS IX_CORE_MESB_SUBSCRIBER_GRGR_ID;
CREATE INDEX IX_CORE_MESB_SUBSCRIBER_GRGR_ID ON CORE.CORE_MESB_SUBSCRIBER (GRGR_ID);
DROP INDEX IF EXISTS IX_CORE_MESB_SUBSCRIBER_LST_NM;
CREATE INDEX IX_CORE_MESB_SUBSCRIBER_LST_NM ON CORE.CORE_MESB_SUBSCRIBER (LST_NM);

DROP INDEX IF EXISTS IX_CORE_MEME_MEMBER_MESB_ID;
CREATE INDEX IX_CORE_MEME_MEMBER_MESB_ID ON CORE.CORE_MEME_MEMBER (MESB_ID);
DROP INDEX IF EXISTS IX_CORE_MEME_MEMBER_IS_ACT;
CREATE INDEX IX_CORE_MEME_MEMBER_IS_ACT ON CORE.CORE_MEME_MEMBER (IS_ACT);
DROP INDEX IF EXISTS IX_CORE_MEME_MEMBER_LST_NM;
CREATE INDEX IX_CORE_MEME_MEMBER_LST_NM ON CORE.CORE_MEME_MEMBER (LST_NM);

DROP INDEX IF EXISTS IX_CORE_SBAD_ADDRESS_MEME_ID;
CREATE INDEX IX_CORE_SBAD_ADDRESS_MEME_ID ON CORE.CORE_SBAD_ADDRESS (MEME_ID);
DROP INDEX IF EXISTS IX_CORE_SBAD_ADDRESS_ST_CD;
CREATE INDEX IX_CORE_SBAD_ADDRESS_ST_CD ON CORE.CORE_SBAD_ADDRESS (ST_CD);
DROP INDEX IF EXISTS IX_CORE_SBAD_ADDRESS_ZIP_CD;
CREATE INDEX IX_CORE_SBAD_ADDRESS_ZIP_CD ON CORE.CORE_SBAD_ADDRESS (ZIP_CD);

DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_MEME_ID;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_MEME_ID ON CORE.CORE_MEEN_ENROLLMENT (MEME_ID);
DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_PLPL_ID;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_PLPL_ID ON CORE.CORE_MEEN_ENROLLMENT (PLPL_ID);
DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_TXN_ID;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_TXN_ID ON CORE.CORE_MEEN_ENROLLMENT (TXN_ID);
DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_ENRL_STAT;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_ENRL_STAT ON CORE.CORE_MEEN_ENROLLMENT (ENRL_STAT);
DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_EFF_DT;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_EFF_DT ON CORE.CORE_MEEN_ENROLLMENT (EFF_DT);
DROP INDEX IF EXISTS IX_CORE_MEEN_ENROLLMENT_MEME_PLPL;
CREATE INDEX IX_CORE_MEEN_ENROLLMENT_MEME_PLPL ON CORE.CORE_MEEN_ENROLLMENT (MEME_ID, PLPL_ID);

DROP INDEX IF EXISTS IX_ENRL_EDXN_TRANSACTION_FILE_NM;
CREATE INDEX IX_ENRL_EDXN_TRANSACTION_FILE_NM ON ENRL.ENRL_EDXN_TRANSACTION (FILE_NM);
DROP INDEX IF EXISTS IX_ENRL_EDXN_TRANSACTION_PROC_STAT;
CREATE INDEX IX_ENRL_EDXN_TRANSACTION_PROC_STAT ON ENRL.ENRL_EDXN_TRANSACTION (PROC_STAT);
DROP INDEX IF EXISTS IX_ENRL_EDXN_TRANSACTION_RCVD_TS;
CREATE INDEX IX_ENRL_EDXN_TRANSACTION_RCVD_TS ON ENRL.ENRL_EDXN_TRANSACTION (RCVD_TS);

DROP INDEX IF EXISTS IX_ENRL_RJRW_REJECT_TXN_ID;
CREATE INDEX IX_ENRL_RJRW_REJECT_TXN_ID ON ENRL.ENRL_RJRW_REJECT (TXN_ID);
DROP INDEX IF EXISTS IX_ENRL_RJRW_REJECT_RJCT_CD;
CREATE INDEX IX_ENRL_RJRW_REJECT_RJCT_CD ON ENRL.ENRL_RJRW_REJECT (RJCT_CD);
DROP INDEX IF EXISTS IX_ENRL_RJRW_REJECT_RJCT_TS;
CREATE INDEX IX_ENRL_RJRW_REJECT_RJCT_TS ON ENRL.ENRL_RJRW_REJECT (RJCT_TS);
