ALTER TABLE IF EXISTS ENRL.ENRL_RJRW_REJECT DROP CONSTRAINT IF EXISTS FK_ENRL_RJRW_REJECT_TXN_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_TXN_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_PLPL_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_MEME_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_SBAD_ADDRESS DROP CONSTRAINT IF EXISTS FK_CORE_SBAD_ADDRESS_MEME_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_MEME_MEMBER DROP CONSTRAINT IF EXISTS FK_CORE_MEME_MEMBER_MESB_ID CASCADE;
ALTER TABLE IF EXISTS CORE.CORE_MESB_SUBSCRIBER DROP CONSTRAINT IF EXISTS FK_CORE_MESB_SUBSCRIBER_GRGR_ID CASCADE;

DROP TABLE IF EXISTS ENRL.ENRL_RJRW_REJECT CASCADE;
DROP TABLE IF EXISTS ENRL.ENRL_EDXN_TRANSACTION CASCADE;
DROP TABLE IF EXISTS CORE.CORE_MEEN_ENROLLMENT CASCADE;
DROP TABLE IF EXISTS CORE.CORE_SBAD_ADDRESS CASCADE;
DROP TABLE IF EXISTS CORE.CORE_MEME_MEMBER CASCADE;
DROP TABLE IF EXISTS CORE.CORE_MESB_SUBSCRIBER CASCADE;
DROP TABLE IF EXISTS CORE.CORE_PLPL_PLAN CASCADE;
DROP TABLE IF EXISTS CORE.CORE_GRGR_GROUP CASCADE;

DROP SCHEMA IF EXISTS ENRL CASCADE;
DROP SCHEMA IF EXISTS CORE CASCADE;
DROP SCHEMA IF EXISTS UTIL CASCADE;
