-- CONSTRAINTS ----------------------------------------------------------------

ALTER TABLE CORE.CORE_MESB_SUBSCRIBER DROP CONSTRAINT IF EXISTS FK_CORE_MESB_SUBSCRIBER_GRGR_ID CASCADE;
ALTER TABLE CORE.CORE_MESB_SUBSCRIBER ADD CONSTRAINT FK_CORE_MESB_SUBSCRIBER_GRGR_ID FOREIGN KEY (GRGR_ID) REFERENCES CORE.CORE_GRGR_GROUP (GRGR_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CORE.CORE_MEME_MEMBER DROP CONSTRAINT IF EXISTS FK_CORE_MEME_MEMBER_MESB_ID CASCADE;
ALTER TABLE CORE.CORE_MEME_MEMBER ADD CONSTRAINT FK_CORE_MEME_MEMBER_MESB_ID FOREIGN KEY (MESB_ID) REFERENCES CORE.CORE_MESB_SUBSCRIBER (MESB_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CORE.CORE_SBAD_ADDRESS DROP CONSTRAINT IF EXISTS FK_CORE_SBAD_ADDRESS_MEME_ID CASCADE;
ALTER TABLE CORE.CORE_SBAD_ADDRESS ADD CONSTRAINT FK_CORE_SBAD_ADDRESS_MEME_ID FOREIGN KEY (MEME_ID) REFERENCES CORE.CORE_MEME_MEMBER (MEME_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_MEME_ID CASCADE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT ADD CONSTRAINT FK_CORE_MEEN_ENROLLMENT_MEME_ID FOREIGN KEY (MEME_ID) REFERENCES CORE.CORE_MEME_MEMBER (MEME_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_PLPL_ID CASCADE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT ADD CONSTRAINT FK_CORE_MEEN_ENROLLMENT_PLPL_ID FOREIGN KEY (PLPL_ID) REFERENCES CORE.CORE_PLPL_PLAN (PLPL_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT DROP CONSTRAINT IF EXISTS FK_CORE_MEEN_ENROLLMENT_TXN_ID CASCADE;
ALTER TABLE CORE.CORE_MEEN_ENROLLMENT ADD CONSTRAINT FK_CORE_MEEN_ENROLLMENT_TXN_ID FOREIGN KEY (TXN_ID) REFERENCES ENRL.ENRL_EDXN_TRANSACTION (TXN_ID) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ENRL.ENRL_RJRW_REJECT DROP CONSTRAINT IF EXISTS FK_ENRL_RJRW_REJECT_TXN_ID CASCADE;
ALTER TABLE ENRL.ENRL_RJRW_REJECT ADD CONSTRAINT FK_ENRL_RJRW_REJECT_TXN_ID FOREIGN KEY (TXN_ID) REFERENCES ENRL.ENRL_EDXN_TRANSACTION (TXN_ID) DEFERRABLE INITIALLY IMMEDIATE;
